name: Generate Games Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run list.js
        run: node auto/list.js

      - name: Run scripts.js
        run: node auto/scripts.js ..
      
      - name: Run title.js
        run: node auto/title.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          git commit -m "Auto-update generated files" || echo "No changes to commit"
          git push
