name: Deploy to Staging

on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    name: Generate Changelog & Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up SSH (for deployment)
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

      # 3️⃣ Generate changelog
      - name: Generate changelog
        uses: m-radmacher/That-Changed@v1.3.0
        # Fallback: generate from last 10 commits if not enough tags
        with:
          from: HEAD~10
          to: HEAD
        env:
          token: ${{ github.token }}
          language: en
          upload: true
          repo: ${{ github.repository }}

      # 4️⃣ Deploy to staging
      - name: Deploy to Staging Server
        run: |
          ssh -o StrictHostKeyChecking=no user@staging.example.com "
            cd /path/to/app &&
            git pull origin main &&
            ./deploy.sh
          "
