name: Update Changelog on Every Commit

on:
  push:
    branches:
      - main
      - release/*

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Get info about the latest commit
      - name: Get commit info
        id: commit
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          AUTHOR=$(git log -1 --pretty=format:'%an')
          MESSAGE=$(git log -1 --pretty=format:'%s')
          FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_HASH | tr '\n' ', ')
          FILES=${FILES%, }  # Remove trailing comma
          echo "hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT
          echo "files=$FILES" >> $GITHUB_OUTPUT

      # 3️⃣ Add table header if it doesn't exist
      - name: Ensure table header
        run: |
          if ! grep -q "| Commit | Author | Message | Files Changed |" README.md; then
            echo "| Commit | Author | Message | Files Changed |" >> README.md
            echo "|--------|--------|---------|---------------|" >> README.md
          fi

      # 4️⃣ Append the commit info as a table row
      - name: Append commit to table
        run: |
          echo "| [${{ steps.commit.outputs.hash }}](https://github.com/${{ github.repository }}/commit/${{ steps.commit.outputs.hash }}) | ${{ steps.commit.outputs.author }} | ${{ steps.commit.outputs.message }} | ${{ steps.commit.outputs.files }} |" >> README.md

      # 5️⃣ Commit and push the updated README
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update changelog for commit ${{ steps.commit.outputs.hash }}" || echo "No changes to commit"
          git push
