name: that-changed

on:
  push:
    branches:
      - main
      - release/*

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate changelog
        uses: m-radmacher/That-Changed@v1.3.0
        env:
          # GitHub personal access token. Defaults to github.token
          token: ${{ github.token }}
          # Language of the changelog (en or de). Defaults to en
          language: en
          # Whether to upload the changelog as a build artifact. Defaults to true
          upload: true
          # Repository to generate the changelog for. Defaults to the current repository (<username>/<repo>)
          repo: ${{ github.repository }}
