name: Update Changelog on Every Commit

on:
  push:
    branches:
      - main
      - release/*

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Get list of changed files in this commit
      - name: Get changed files
        id: changed
        run: |
          # Get commit hash
          COMMIT_HASH=$(git rev-parse HEAD)
          # Get author and message
          AUTHOR=$(git log -1 --pretty=format:'%an')
          MESSAGE=$(git log -1 --pretty=format:'%s')
          # Get list of changed files
          FILES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_HASH | tr '\n' ', ')
          # Remove trailing comma and space
          FILES=${FILES%, }
          # Save for next step
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT
          echo "files=$FILES" >> $GITHUB_OUTPUT

      # 3️⃣ Append info to README.md (or CHANGELOG.md)
      - name: Append to README.md
        run: |
          echo "" >> README.md
          echo "## Commit ${{ steps.changed.outputs.commit_hash }}" >> README.md
          echo "- Author: ${{ steps.changed.outputs.author }}" >> README.md
          echo "- Message: ${{ steps.changed.outputs.message }}" >> README.md
          echo "- Files changed: ${{ steps.changed.outputs.files }}" >> README.md

      # 4️⃣ Commit and push the updated README
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update changelog for commit ${{ steps.changed.outputs.commit_hash }}" || echo "No changes to commit"
          git push
