name: Deploy to Staging

on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    name: Generate Changelog & Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Generate changelog
      - name: Generate changelog
        uses: m-radmacher/That-Changed@v1.3.0
        with:
          from: HEAD~10
          to: HEAD
        env:
          token: ${{ github.token }}
          language: en
          upload: true
          repo: ${{ github.repository }}

      # 3️⃣ Deploy to staging (example: build & push Docker image)
      - name: Deploy to staging
        run: |
          echo "Running deployment steps..."
          # Example: build Docker image
          docker build -t my-app:staging .
          # Push to a registry (use a secret for authentication)
          # docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          # docker push my-app:staging
